// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/docs.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/spbenj.tsx";
import * as $4 from "./routes/spgold.tsx";
import * as $5 from "./routes/sphall.tsx";
import * as $6 from "./routes/spsull.tsx";
import * as $$0 from "./islands/Footer.tsx";
import * as $$1 from "./islands/Header.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/docs.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/spbenj.tsx": $3,
    "./routes/spgold.tsx": $4,
    "./routes/sphall.tsx": $5,
    "./routes/spsull.tsx": $6,
  },
  islands: {
    "./islands/Footer.tsx": $$0,
    "./islands/Header.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
